### ISSUE TITLE
Getting a RecvError() no matter what I do

### ISSUE THREAD

**Issue by kaspar-p** [mvniekerk/tokio-cron-scheduler#57]
I use this library to run a twitter bot, but I must have changed something, and lately every time the cron job actually starts, it stops immediately with a generic error:
```
2023-11-14T01:00:00.196354Z ERROR tokio_cron_scheduler::job::creator: /home/pi/.cargo/registry/src/index.crates.io-1cd66030c949c28d/tokio-cron-scheduler-0.9.4/src/job/creator.rs: Error running job a67d2389-3be4-4ca8-8b70-8afd7a202170 RecvError(())
```
and I'm not sure how to debug. I've put the contents of the job into a `cron_tweet()` fn, and doing something like:
```rs
let hour_offset = 1;
scheduler
    .add(
        // 6pm MST is midnight UTC
        Job::new_async(format!("0 0 {} * * *", hour_offset).as_str(), |_, __| {
            Box::pin(async move {
                cron_tweet().await;
            })
        })
        .unwrap(),
    )
    .await
    .unwrap();
```
has the error, but just:
```rs
cron_tweet().await;
```
works fine.

The start of my `cron_tweet()` function is:
```
async fn cron_tweet() -> () {
    info!("Starting cron...");
    let config: Config = get_config().expect("Getting config failed!");
    let dao = match ant_data_farm::connect_config(config.database).await {
        Err(e) => {
            error!("Failed to initialize database: {}", e);
            error!("Ending CRON early!");
            return;
        }
        Ok(dao) => dao,
    };

  ...
```
where the `dao` is a database connection. And I actually see the `Starting cron...` logs:
```
2023-11-14T00:55:45.953573Z  INFO ant_who_tweets: projects/ant-who-tweets/src/main.rs: Saw 255 seconds until next job, sleeping for 255 seconds!
2023-11-14T01:00:00.148506Z  INFO ant_who_tweets: projects/ant-who-tweets/src/main.rs: Starting cron...
2023-11-14T01:00:00.196354Z ERROR tokio_cron_scheduler::job::creator: /home/pi/.cargo/registry/src/index.crates.io-1cd66030c949c28d/tokio-cron-scheduler-0.9.4/src/job/creator.rs: Error running job a67d2389-3be4-4ca8-8b70-8afd7a202170 RecvError(())
```
but then immediately the error. The manual way (no scheduler, just calling `cron_tweet().await` directly, has all the right logging).

What could RecvError() come from? Why does this happen? It doesn't seem like a bad connection to the DB, or my `error!` logs would appear, but they aren't...

**Comment by RoloEdits** [comment]
version 0.9.4
tokio version 1.35.1

Just had this happen as well. Been running fine for a week then suddenly today I get this in my logs.  I have error reporting for my own things and had nothing show up there. 

its being reported here, line 96:
https://github.com/mvniekerk/tokio-cron-scheduler/blob/da2e31087603661e6b4a7679cb4cde72e0ae130e/src/job/creator.rs#L94-L104

From what I can gather, tokio has three errors with this name:
![image](https://github.com/mvniekerk/tokio-cron-scheduler/assets/12489689/fa5314fc-0922-4d4b-b769-d6beda575a9c)

seems to have something to do with channels?

**Comment by kaspar-p** [comment]
Yep, I think there must be some kind of race condition within the library. You can see in my Git history [link](https://github.com/kaspar-p/types-of-ants/compare/dd72f85c083cddfa9854db65741aa974a3f0f091..b11ab0a16a6d984f6a8039fd5c53a1556dbec83f#diff-37fa9283abe40fa38ecda2ff680e3627715f9018f16e1b9fe6ba4c8064e06744) that very minor things change, and this error no longer affects me today.

Really, I added some logging, and things fixed themselves.

**Comment by hedon954** [comment]
me too...

```bash
2024-09-10T07:00:00.282823Z  INFO hedon_bot::cron_task: Run go_official_blog 2024-09-11 07:00:00 UTC
2024-09-10T07:00:00.282919Z ERROR tokio_cron_scheduler::job::creator: Error running job 7a8fab45-ab4d-4c5c-b57e-3c77f2dd2b43 RecvError(())
2024-09-10T07:50:00.011838Z  INFO hedon_bot::cron_task: Run redis_official_blog 2024-09-10 08:50:00 UTC
2024-09-10T07:50:00.016983Z ERROR tokio_cron_scheduler::job::creator: Error running job 2d6a8cf1-fb6f-48fb-a483-58c5f950b600 RecvError(())
2024-09-10T10:50:00.381384Z  INFO hedon_bot::cron_task: Run redis_official_blog 2024-09-10 11:50:00 UTC
2024-09-10T10:50:00.381490Z ERROR tokio_cron_scheduler::job::creator: Error running job 2d6a8cf1-fb6f-48fb-a483-58c5f950b600 RecvError(())
```

**Comment by huwence** [comment]
me too...
2024-11-13 21:24:00.65259133 [ERROR] [/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-cron-scheduler-0.10.2/src/job/creator.rs:96] Error running job b60d3076-ce96-4aba-bb9c-8f6715c19665 RecvError(())

**Comment by kaspar-p** [comment]
Ok, I have a twitter bot with a beta environment (twitter (at) `typesofants` and twitter (at) `betatypesofants`), running the EXACT same code. The production one is working (tweeted yesterday, does daily tweets) and the beta one is not.

I have a hunch that this is just the error message that happens when the USER CODE panics in some way, without returning a sane error code.

I wrote a little test program:
```rs
use chrono::Utc;
use std::time::Duration;
use tokio_cron_scheduler::{Job, JobScheduler};
use tracing::info;

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let scheduler = JobScheduler::new().await?;

    scheduler
        .add(Job::new_async("*/2 * * * * *", |_, __| {
            Box::pin(async move {
                panic!("Failed at: {}", Utc::now());
            })
        })?)
        .await?;

    // Start the scheduler
    scheduler.start().await?;

    loop {
        info!("Sleeping 1800 seconds...");
        tokio::time::sleep(Duration::from_secs(1800)).await;
    }
}
```

which panics every two seconds.

Running this, I get:

```
2026-03-20T15:11:10.429104Z ERROR tokio_cron_scheduler::job::creator: /Users/kasparpoland/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-cron-scheduler-0.14.0/src/job/creator.rs:96: Error running job d800a8aa-5da3-4470-be41-fc1b2e84df4a RecvError(())

thread 'tokio-runtime-worker' (683776) panicked at projects/ant-who-tweets/src/bin/libtest.rs:18:17:
Failed at: 2026-03-20 15:11:12.435916 UTC
2026-03-20T15:11:12.435990Z ERROR tokio_cron_scheduler::job::creator: /Users/kasparpoland/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-cron-scheduler-0.14.0/src/job/creator.rs:96: Error running job d800a8aa-5da3-4470-be41-fc1b2e84df4a RecvError(())

thread 'tokio-runtime-worker' (683776) panicked at projects/ant-who-tweets/src/bin/libtest.rs:18:17:
Failed at: 2026-03-20 15:11:14.444766 UTC
2026-03-20T15:11:14.444835Z ERROR tokio_cron_scheduler::job::creator: /Users/kasparpoland/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-cron-scheduler-0.14.0/src/job/creator.rs:96: Error running job d800a8aa-5da3-4470-be41-fc1b2e84df4a RecvError(())

thread 'tokio-runtime-worker' (683774) panicked at projects/ant-who-tweets/src/bin/libtest.rs:18:17:
Failed at: 2026-03-20 15:11:16.453440 UTC
2026-03-20T15:11:16.453514Z ERROR tokio_cron_scheduler::job::creator: /Users/kasparpoland/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-cron-scheduler-0.14.0/src/job/creator.rs:96: Error running job d800a8aa-5da3-4470-be41-fc1b2e84df4a RecvError(())
```

So definitely, `RecvError(())` is what happens when user code panics. I still get a sane error message here, which I'm not seeing in my code or in the examples other folks have left above, though, so that's still a mystery.

**EDIT:**

I don't get a sane message because for some reason, my deployment setup (binary run by systemd) was suppressing the stderr from entering my `logs/*.log` files, but I actually do see the original error with journalctl:
```
Mar 20 00:00:01 antworker002 ant-who-tweets[12376]: posting tweet: Api(ApiError { title: "Service Unavailable", kind: "about:blank", status: 503, detail: "Service Unavailable", errors: [] })
Mar 20 00:00:01 antworker002 ant-who-tweets[12376]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
with `sudo journalctl -xeu ant-who-tweets`.
